### ISSUE TITLE
Could the pipeline be used to  the data of nanopore direct RNA sequencing?

### ISSUE THREAD

**Issue by q1134269149** [iMetOsaka/UNAGI#1]
Hi,
   Thank you very much for providing us with this pipeline to process nanopore data. I read your research paper, and the data of **nanopore full-length cdna sequencin**g was used to analyse. 
   Because I got my data with **nanopore direct RNA sequencing** and the sequence of bases in these reads extends from 3' to 5'  which is backward to the cdna sequencing, could the pipeline be used to  my data of **nanopore direct RNA sequencing**? Looking forward to your reply.
Thanks
hqin

**Comment by malkadi89** [comment]
Thank you for your interest in our pipeline and very sorry for the late response. In my experience, the base-caller (Guppy) will produce the sequences in fastq file in the right direction 5' to 3' and thus our pipeline is totally compatible with DRS.  Please let us know if you have any problems. 

Kind Regards,

**Comment by JungNicolas** [comment]
I'm closing this issue since it seems solved for the moment.
