### ISSUE TITLE
Error in combinedCoverage calculation?

### ISSUE THREAD

**Issue by mglubber** [iMetOsaka/UNAGI#2]
When calculating the combined coverage of chromosome, it looks like the 'negative part' of coverage is calculated from the wrong file, which means the combined coverage will always be exactly twice the positive coverage.
https://github.com/iMetOsaka/UNAGI/blob/5a937145a67f112376b749587b71cec12f9ba26b/app/unagi.py#L681
I'm assuming this should be `negparts=negline.split("\t") `

**Comment by JungNicolas** [comment]
Hello ! Sorry for the delay in answering you. 
You're very right and I have corrected this error in the latest version.
Thank you very much !
